# Generated by Django 3.2.5 on 2022-03-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_pw',
        ),
    ]
