# Generated by Django 3.2.5 on 2022-03-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220303_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
