# Generated by Django 3.2.5 on 2022-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatZip_Name', models.CharField(max_length=20)),
                ('MatZip_Address', models.CharField(max_length=50)),
                ('MatZip_Time', models.CharField(max_length=100)),
                ('MatZip_PhoneN', models.CharField(max_length=15)),
                ('MatZip_DesC', models.CharField(max_length=50)),
                ('MatZip_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_content', models.CharField(max_length=200)),
                ('r_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
