# Generated by Django 3.2.5 on 2022-02-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matzip',
            name='MatZip_latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matzip',
            name='MatZip_longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
