# Generated by Django 3.2.5 on 2022-02-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodplace', '0003_auto_20220225_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matzip',
            name='MatZip_latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='matzip',
            name='MatZip_longitude',
            field=models.CharField(max_length=20),
        ),
    ]
