# Generated by Django 3.2.5 on 2022-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodplace', '0004_auto_20220225_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='r_rating',
            field=models.IntegerField(default=0),
        ),
    ]
