# Generated by Django 3.2.5 on 2022-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodplace', '0005_review_r_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='matzip',
            name='MatZip_review_count',
            field=models.IntegerField(default=0),
        ),
    ]
